### ISSUE TITLE
Import favorites items instead of manually define them

### ISSUE THREAD

**Issue by groenmarsmannetje** [Chouffy/home_assistant_tgtg#2]
For me the whole configuration is not clearly described.
For instance I do not have a password for my account. 
When I login with the TGTG iPhone app I use my email address.
Then I get an email with a login button and numeric code to login.
Is this numeric code (one-time-password?) the password that I should use?

> Update: 
> I tried to use that numeric code with the "get items" script but it doesn't work, that gives an authentication failure. 
> But I got an email that I tried to logon from different device and that email also contained a link to reset password. After resetting and using that password it worked.

I also do not understand why my favourites are not used by default. 
The upstream component seems to support that. 
Instead I need to use a python script to get these. That is not user friendly at all (it only works for developers that are familiair with running python scripts). I would expect that I can just pick the items when I setup the configuration preferably in the Home Assistant UI.

How to get the api secrets as alternative for username and password is not well documented.

I am in the Netherlands BTW

**Comment by Chouffy** [comment]
Hi,

Thanks for your comment 😊

Regarding the login using username/password, 
The current setup isn't interactive (= everything is fixed in configuration.yaml), so I don't see how and where we could ask the user to input the receive PIN code.
Good to hear that you find a way to reset your password, I updated the Readme to hint that.

Regarding tokens,
I would love to set up an interactive setup using the Home Assistant UI.
Sadly I lack the skills and time to do that ... I would be very happy if somebody take that up 😕
I'll track this in a separate issue.

Regarding why I didn't choose to setup favorites by default,
I didn't used like this, but it should be possible to do it. I don't promise anything, but I'll look at it!
In the meantime this issue will be used to discuss this if that's ok for you.

**Comment by groenmarsmannetje** [comment]
Thank you, I have got it working now with username and password.
Great way to be notified and be the first to make a reservation for the TGTG package.

 Still struggling to get API credentials in my own script, but must be because it is my first python code.

**Comment by Chouffy** [comment]
@groenmarsmannetje could you try this script? it should tell you all the 3 tokens you need :)
https://github.com/Chouffy/home_assistant_tgtg/blob/main/tgtg_get_tokens.py

**Comment by Chouffy** [comment]
Hey there,

I had some free time: now favorites are fetch if you don't define `item:` 😊
Related release: https://github.com/Chouffy/home_assistant_tgtg/releases/tag/3.0.0
Check the Readme on the home page!

I'll close this issue now, but feel free to comment here

**Comment by groenmarsmannetje** [comment]
Thank you very much. I can confirm that the script works.
