### ISSUE TITLE
Is scan_interval used?

### ISSUE THREAD

**Issue by DavidDeSloovere** [Chouffy/home_assistant_tgtg#36]
I don't see any reference to `scan_interval` in the code, and also don't see my items updated.
What's going on here?

**Comment by Chouffy** [comment]
Hey @DavidDeSloovere , 
`scan_interval` is a Home Assistant property, not one define by this module. So yes it is used and should work just fine to indicate the refresh period in seconds of the sensors. 
If you don't see your items updated, the cause is probably elsewhere - take a look at your logs and post another issue of you think there's something wrong with the module :)
